# Generated by Django 5.1.3 on 2024-11-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='photos/'),
        ),
    ]
